# Minimal config compatible with Supabase CLI

# --- Individual functions ---

[functions.validate-youtube]
enabled = true
verify_jwt = true
entrypoint = "./functions/validate-youtube/index.ts"

[functions.referral-redirect]
enabled = true
verify_jwt = false
entrypoint = "./functions/referral-redirect/index.ts"

[functions.create-checkout-session]
enabled = true
verify_jwt = true
entrypoint = "./functions/create-checkout-session/index.ts"

[functions.stripe-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/stripe-webhook/index.ts"

[functions.cancel-subscription]
enabled = true
verify_jwt = true
entrypoint = "./functions/cancel-subscription/index.ts"

[functions.delete-account]
enabled = true
verify_jwt = true
entrypoint = "./functions/delete-account/index.ts"

[functions.videos-start-upload]
enabled = true
verify_jwt = true
import_map = "./functions/videos-start-upload/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/videos-start-upload/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/videos-start-upload/*.html" ]

[functions.videos-finish]
enabled = true
verify_jwt = true
import_map = "./functions/videos-finish/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/videos-finish/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/videos-finish/*.html" ]
